name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker rm -f my-interior-shop
           docker build . --file Dockerfile --tag my-interior-shop
           docker compose up -d
